#!/usr/bin/env bash

echo "Installing neovim"
sudo add-apt-repository -y ppa:neovim-ppa/unstable
sudo apt-get update
sudo apt-get install -y neovim

echo "Installing ruby client for neovim"
sudo gem install --verbose neovim --no-ri --no-rdoc

echo "Creating backup dirs"
mkdir -p _backup
mkdir -p _temp

echo "Installing plugins"
nvim +PlugInstall +qall
